version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/tffumpt
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X main.version=v{{ .Version }}

archives:
  - formats: [zip]
    name_template: >-
      {{ .ProjectName }}-
      {{- printf "v%s" .Version }}-
      {{- .Os }}-
      {{- .Arch }}

checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}-checksums.txt"
